#' Generate Kaplan-Meier curves with prediction intervals from simulation routine
#'
#' @export
#' @param sim A `trialsim` class object generated by [trial_sim()] function.
#'
calc_km <- function(sim){

t.last <- survival::survfit(Surv(pfst, status)~1, data = sim$sim)$time %>% max()
t.out <- seq(0, t.last, length.out = 100)

approx_km <- function(x){
  surv <- stats::approx(c(0,x$time), c(1,x$surv), xout=t.out, method="constant", rule=2)$y
  tibble::tibble(time = t.out, surv = surv)
}

  sim.grouped <-
    sim$sim %>%
    dplyr::group_by(rep, rx) %>% tidyr::nest()

  sim.km <-
    sim.grouped %>%
    # Fit each nested data to KM
    dplyr::mutate(kmfit =
                    purrr::map(data, function(x) survival::survfit(Surv(pfst, status)~1, data=x))) %>%
    dplyr::mutate(median = purrr::map_dbl(kmfit, function(x) broom::glance(x)$median),
                  n = purrr::map_dbl(kmfit, function(x) broom::glance(x)$nobs),
                  km = purrr::map(kmfit, approx_km)) %>%
    dplyr::arrange(rep,rx)

  ci.range <- 0.95

  sim.km.quantile <-
    sim.km %>%
    dplyr::select(-data, -kmfit) %>%
    tidyr::unnest(km) %>%
    dplyr::group_by(rx, time) %>%
    tidyr::nest() %>%
    dplyr::mutate(quantiles = purrr::map(data, function(x)
      dplyr::summarize(x,
                       int_low = stats::quantile(surv, probs = 0.5 - ci.range/2),
                       int_med = stats::quantile(surv, probs = 0.5),
                       int_high= stats::quantile(surv, probs = 0.5 + ci.range/2)))) %>%
    tidyr::unnest(quantiles) %>%
    dplyr::ungroup() %>%
    dplyr::select(-data)

  ## Calc quantiles for median survival time
  sim.median.time <-
    sim.km %>%
    dplyr::select(rep, rx, median, n) %>%
    dplyr::ungroup()

  quantiles <-
    tibble::tibble(description = c("int_low", "int_med", "int_high"),
                   quantile = c(0.5 - ci.range/2, 0.5, 0.5 + ci.range/2))

  sim.median.quantile <-
    sim.median.time %>%
    dplyr::group_by(rx) %>%
    dplyr::summarize(int_low = as.numeric(stats::quantile(median, probs = 0.5 - ci.range/2, na.rm = TRUE)),
                   int_med = as.numeric(stats::quantile(median, probs = 0.5, na.rm = TRUE)),
                   int_high= as.numeric(stats::quantile(median, probs = 0.5 + ci.range/2, na.rm = TRUE)),
                   n_min = min(n),
                   n_max = max(n)) %>%
    dplyr::ungroup() %>%
    tidyr::pivot_longer(int_low:int_high, names_to = "description", values_to = "median") %>%
    dplyr::inner_join(quantiles,by="description")

  # Output
  out <- list()
  out$sim.km.quantile <- sim.km.quantile
  out$median.quantile <- sim.median.quantile
  structure(out, class = c("trialsim.km"))
}
