#' Generate statistics from simulation runs on Kaplan-Meier medians
#'
#' @export
#' @param sim A `trialsim` class object generated by [trial_sim()] function.
#' @param ci.range Prediction interval for simulated survival KM medians (defaults to 0.95).
#' @return A `trialsim.km` object that contains a data frame (tibble) for the KM medians of each simulation with the
#'   following columns:
#'   \itemize{\item \strong{rep}: ID for simulation runs
#'            \item \strong{rx}: Treatment group
#'            \item \strong{median}: KM median for each simulation
#'            }
#'   And a data frame containing the summary statistics for KM medians across simulations:
#'   \itemize{\item \strong{rx}: Treatment group
#'            \item \strong{description}: Labels for KM statistics: lower limit \ median \ upper limit
#'            \item \strong{KM_median}: Statistic for KM medians
#'            \item \strong{quantile}: Quantile of simulations (corresponding to `ci.range` parameter)
#'            }
#' @details
#' Extracts median and prediction interval by treatment group across all repeated simulations for median survival.
#'
#' @examples
#' # Generate some trial simulation data
#' enrol <- c(seq(2,10,length.out=5),rep(10,times=3))
#' schedule <- seq(0,100,4)
#' sim <- trial_sim(schedule, enrol, c(12,10), 40, adjust=TRUE, trt=c("Sip-T","Placebo"),
#' death.prop=0.1, censor.prop=0.1, n.rep=1000)
#' # Extract Kaplan-Meier results on simulated data
#' \donttest{sim.km <- calc_km(sim)}
calc_km <- function(sim,ci.range=0.95){
  if(!(any(names(sim$sim)=="eventt"))) sim$sim <- sim$sim %>% dplyr::mutate(eventt=pfst)
  sim.grouped <-
    sim$sim %>%
    dplyr::group_by(rep, rx) %>% tidyr::nest()

  sim.km <-
    sim.grouped %>%
    # Fit each nested data to KM
    dplyr::mutate(kmfit =
                    purrr::map(data, function(x) survival::survfit(survival::Surv(eventt, status)~1, data=x))) %>%
    dplyr::mutate(median = purrr::map_dbl(kmfit, function(x) broom::glance(x)$median)) %>%
    dplyr::arrange(rep,rx) %>% dplyr::select(!c(data,kmfit))

  ## Calc quantiles for median survival time

  quantiles <-
    tibble::tibble(description = c("sim_low", "sim_median", "sim_high"),
                   quantile = c(0.5 - ci.range/2, 0.5, 0.5 + ci.range/2))

  sim.median.quantile <- sim.km %>%
    dplyr::group_by(rx) %>%
    dplyr::summarize(sim_low = stats::quantile(median, probs = 0.5 - ci.range/2, na.rm = TRUE),
                   sim_median = stats::quantile(median, probs = 0.5, na.rm = TRUE),
                   sim_high= stats::quantile(median, probs = 0.5 + ci.range/2, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    tidyr::pivot_longer(sim_low:sim_high, names_to = "description", values_to = "KM_median") %>%
    dplyr::inner_join(quantiles,by="description")

  # Output
  out <- list()
  out$sim.km <- sim.km %>% dplyr::ungroup()
  out$median.quantile <- sim.median.quantile
  structure(out, class = c("trialsim.km"))
}
