#' Generate Kaplan-Meier curves with prediction intervals from simulation routine
#'
#' @export
#' @param sim A `trialsim` class object generated by [trial_sim()] function.
#'
calc_km <- function(sim){

t.last <- survival::survfit(Surv(pfst, status)~1, data = sim$sim)$time %>% max()
#t.out <- seq(0, t.last, length.out = 100)
t.out <- seq(0,132,12)

approx_km <- function(x){
  surv <- stats::approx(c(0,x$time), c(1,x$surv), xout=t.out, method="constant", rule=2)$y
  tibble::tibble(time = t.out, surv = surv)
}

  sim.grouped <-
    sim$sim %>%
    dplyr::group_by(rep, rx) %>% tidyr::nest()

  sim.km <-
    sim.grouped %>%
    # Fit each nested data to KM
    dplyr::mutate(kmfit =
                    purrr::map(data, function(x) survival::survfit(Surv(pfst, status)~1, data=x))) %>%
    dplyr::mutate(median = purrr::map_dbl(kmfit, function(x) broom::glance(x)$median)) %>%
    dplyr::arrange(rep,rx) %>% select(-data,-kmfit)

  ci.range <- 0.95


  ## Calc quantiles for median survival time


  quantiles <-
    tibble::tibble(description = c("int_low", "int_med", "int_high"),
                   quantile = c(0.5 - ci.range/2, 0.5, 0.5 + ci.range/2))

  sim.median.quantile <-
    sim.km %>% ungroup() %>%
    dplyr::group_by(rx) %>%
    dplyr::summarize(int_low = as.numeric(stats::quantile(median, probs = 0.5 - ci.range/2, na.rm = TRUE)),
                   int_med = as.numeric(stats::quantile(median, probs = 0.5, na.rm = TRUE)),
                   int_high= as.numeric(stats::quantile(median, probs = 0.5 + ci.range/2, na.rm = TRUE))) %>%
    dplyr::ungroup() %>%
    tidyr::pivot_longer(int_low:int_high, names_to = "description", values_to = "median") %>%
    dplyr::inner_join(quantiles,by="description")

  # Output
  out <- list()
  out$sim.km <- sim.km
  out$median.quantile <- sim.median.quantile
  structure(out, class = c("trialsim.km"))
}
#' @export
plot_sim <- function(sim) UseMethod("plot_sim")
#' @export
plot_sim.trialsim.km <- function(sim, ci = FALSE){

  # Plot
  ## Generate ggplot object with aes specified using simulated data
  #sim <- sim.km
  kmplot <- sim$sim.km
  kmquantile <- sim$median.quantile
  km1 <- kmquantile %>% filter(rx==0) %>% select(-rx)
  km2 <- kmquantile %>% filter(rx==1) %>% select(-rx)

  g <-
    ggplot2::ggplot(kmplot, ggplot2::aes(median)) +
    ggplot2::geom_histogram(bins = 30, alpha = 0.5, color = "black") +
    ggplot2::geom_vline(data = dplyr::filter(kmquantile, description %in% c("int_low", "int_high")),
                        aes(xintercept = median), lty="dashed", color="red", lwd=1) +
    ggplot2::facet_wrap(~rx)
  tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)),
                       base_size = 10,
                       padding = unit(c(2, 4), "mm"))
  tbl1 <- tableGrob(km1, rows=NULL, theme=tt)
  tbl2 <- tableGrob(km2, rows=NULL, theme=tt)
  hlay <- rbind(c(1,1),
                c(2,3))
  g <- grid.arrange(g, tbl1, tbl2, layout_matrix=hlay,
               heights = c(2, 1))
  return(g)
}

