#' Generate statistics from simulation runs on hazard ratios
#'
#' @export
#' @param sim A `trialsim` class object generated by [trial_sim()] function.
#' @param ci.range Prediction interval for simulated hazard ratios (defaults to 0.95).
#' @return A `trialsim.hr` object that contains a data frame (tibble) for the hazard ratios of each simulation
#' with the following columns:
#'   \itemize{\item \strong{rep}: ID for simulation runs
#'            \item \strong{HR}: hazard ratio for each simulation
#'            }
#' And a data frame containing the summary statistics for hazard ratios across simulations:
#'   \itemize{\item \strong{description}: Labels for hazard ratios: lower limit \ median \ upper limit
#'            \item \strong{HR}: Statistic for hazard ratios
#'            \item \strong{quantile}: Quantile of simulations (corresponding to `ci.range` parameter)
#'            }
#' @details
#' Extracts median and prediction interval by treatment group across all repeated simulations for hazard ratio.
#'
#' @examples
#' # Generate some trial simulation data
#' enrol <- c(seq(2,10,length.out=5),rep(10,times=3))
#' schedule <- seq(0,100,4)
#' sim <- trial_sim(schedule, enrol, c(12,10), 40, adjust=TRUE, trt=c("Sip-T","Placebo"),
#' death.prop=0.1, censor.prop=0.1, n.rep=1000)
#' # Extract hazard ratios from simulated data
#' \donttest{sim.hr <- calc_hr(sim)}
calc_hr <- function(sim,ci.range=0.95){
  if(!(any(names(sim$sim)=="eventt"))) sim$sim <- sim$sim %>% dplyr::mutate(eventt=pfst)
  sim.nested <-
    sim$sim %>% dplyr::group_by(rep) %>% tidyr::nest()

  calc_hr_each_sim <- function(x){
    cfit <- survival::coxph(survival::Surv(eventt, status)~rx, data=x) %>%
      broom::tidy(exponentiate = TRUE) %>%
      dplyr::select(HR=estimate)
    return(cfit)
  }
  sim.hr <-
    sim.nested %>%
    dplyr::mutate(HR = purrr::map(data, calc_hr_each_sim)) %>%
    tidyr::unnest(HR) %>% dplyr::select(-data) %>% dplyr::ungroup()

  quantiles <-
    tibble::tibble(description = c("sim_low", "sim_median", "sim_high"),
                   quantile = c(0.5 - ci.range/2, 0.5, 0.5 + ci.range/2))

  sim.hr.quantile <-
    sim.hr %>%
    dplyr::summarize(sim_low = stats::quantile(HR, probs = 0.5 - ci.range/2, na.rm = TRUE),
                     sim_median = stats::quantile(HR, probs = 0.5, na.rm = TRUE),
                     sim_high= stats::quantile(HR, probs = 0.5 + ci.range/2, na.rm = TRUE)) %>%
    tidyr::pivot_longer(sim_low:sim_high, names_to = "description", values_to = "HR") %>%
    dplyr::inner_join(quantiles,by="description")
  # Output
  out <- list()
  out$sim.hr <- sim.hr
  out$sim.hr.quantile <- sim.hr.quantile
  structure(out, class = c("trialsim.hr"))
}

